### PR TITLE
Require sudo in .travis.yml

### PR DESCRIPTION
**Pull request by andreasnoack**
This should make it possible to install HDF5. Let's see.

### CODE REVIEW

**Comment by sbromberger** [comment]
Thank you, @andreasnoack - brilliant!!

**Comment by andreasnoack** [comment]
You are welcome. If you could make a release then can proceed with https://github.com/JuliaLang/METADATA.jl/pull/13313 without breaking anybody's GraphIO.jl.

**Comment by sbromberger** [comment]
Was just tagging it now. Stand by.

**Comment by sbromberger** [comment]
ref: https://github.com/JuliaLang/METADATA.jl/pull/13343

**Pull request merged**
