### PR TITLE
remove Requires

### PR DESCRIPTION
**Pull request by GiggleLiu**
Remove conditional dependencies.

```julia
# GraphIO alone
julia> @time using GraphIO
  1.376940 seconds (3.12 M allocations: 221.025 MiB, 2.51% gc time, 32.49% compilation time)
```

```julia
# Remove Requires and restart
julia> @time using GraphIO
  1.775102 seconds (3.73 M allocations: 253.879 MiB, 2.98% gc time, 44.93% compilation time)
```

### CODE REVIEW

**Comment by filchristou** [comment]
is there any reason why this is not merged ? Is there any other plans for the future design of this package ?

**Comment by simonschoelly** [comment]
I guess nobody had time yet. In any case, it is something that needs to be discussed anyway, as there was a reason why we added Requires - I can't exactly rembember why, although I was the one who did the changes.

It is also nothing urgent, as no bugs are fixed and no new features are added.

**Comment by GiggleLiu** [comment]
> I guess nobody had time yet. In any case, it is something that needs to be discussed anyway, as there was a reason why we added Requires - I can't exactly rembember why, although I was the one who did the changes.
> 
> It is also nothing urgent, as no bugs are fixed and no new features are added.

I fix it because there are a lot bugs, I just can not load graph6 module.
And keno find the similar bug. Well, I forgot to mention those bugs in the pr.

**Comment by gdalle** [comment]
This should probably be done with extensions now

**Comment by filchristou** [comment]
yes, can we close this ?

**Pull request closed without merging**
